### ISSUE TITLE
Missing dependencies in frontend

### ISSUE THREAD

**Issue by John15321** [PWr-Aerospace/ground-control-station#3]
### Description

Missing dependencies in frontend cause runtime errors:

```bash
  VITE v4.3.3  ready in 393 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching /home/jkaszowski/worktime/ground-control-station/src-tauri for changes...
   Compiling ground-control-station v0.0.0 (/home/jkaszowski/worktime/ground-control-station/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 16.27s
Got the lock
In the main loop
2:12:54 AM [vite] Internal server error: Failed to resolve import "react-chartjs-2" from "src/App.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/jkaszowski/worktime/ground-control-station/src/App.tsx:7:21
  21 |  import "./styles.css";
  22 |  import { invoke } from "@tauri-apps/api/tauri";
  23 |  import { Line } from "react-chartjs-2";
     |                        ^
  24 |  import { Chart as ChartJS, Tooltip } from "chart.js";
  25 |  import { dialog } from "@tauri-apps/api";
      at formatError (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:42603:46)
      at TransformContext.error (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:42599:19)
      at normalizeUrl (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:40509:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:40652:47
      at async Promise.all (index 9)
      at async TransformContext.transform (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:40578:13)
      at async Object.transform (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:42877:30)
      at async loadAndTransform (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:53334:29)
Failed to resolve import "react-chartjs-2" from "src/App.tsx". Does the file exist?
2:12:54 AM [vite] Internal server error: Failed to resolve import "react-chartjs-2" from "src/App.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/jkaszowski/worktime/ground-control-station/src/App.tsx:7:21
  21 |  import "./styles.css";
  22 |  import { invoke } from "@tauri-apps/api/tauri";
  23 |  import { Line } from "react-chartjs-2";
     |                        ^
  24 |  import { Chart as ChartJS, Tooltip } from "chart.js";
  25 |  import { dialog } from "@tauri-apps/api";
      at formatError (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:42603:46)
      at TransformContext.error (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:42599:19)
      at normalizeUrl (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:40509:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:40652:47
      at async Promise.all (index 9)
      at async TransformContext.transform (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:40578:13)
      at async Object.transform (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:42877:30)
      at async loadAndTransform (file:///home/jkaszowski/worktime/ground-control-station/node_modules/vite/dist/node/chunks/dep-a178814b.js:53334:29)
Vim: Warning: Input is not from a terminal
Vim: Caught deadly signal TERM

Vim: Finished.
```

**Comment by John15321** [comment]
The dependencies arent missing, the `npm install` command needs to be run so that the node dependencies are installed. The solution to that issue is to add that step to the README
